INSERT INTO city(city, date_created) VALUES ('CBD', now());
INSERT INTO city(city, date_created) VALUES ('Chinatown', now());
INSERT INTO city(city, date_created) VALUES ('Marina Bay', now());
INSERT INTO city(city, date_created) VALUES ('Shenton Way', now());
INSERT INTO city(city, date_created) VALUES ('Tanjong Pagar', now());
INSERT INTO city(city, date_created) VALUES ('Queenstown', now());
INSERT INTO city(city, date_created) VALUES ('Tiong Bahru', now());
INSERT INTO city(city, date_created) VALUES ('Keppel', now());
INSERT INTO city(city, date_created) VALUES ('Sentosa', now());
INSERT INTO city(city, date_created) VALUES ('Telok Blangah', now());
INSERT INTO city(city, date_created) VALUES ('Buona Vista', now());
INSERT INTO city(city, date_created) VALUES ('West Coast', now());
INSERT INTO city(city, date_created) VALUES ('City Hall', now());
INSERT INTO city(city, date_created) VALUES ('North Bridge Road', now());
INSERT INTO city(city, date_created) VALUES ('Beach Road', now());
INSERT INTO city(city, date_created) VALUES ('Bugis', now());
INSERT INTO city(city, date_created) VALUES ('Rochor', now());
INSERT INTO city(city, date_created) VALUES ('Little India', now());
INSERT INTO city(city, date_created) VALUES ('Serangoon Road', now());
INSERT INTO city(city, date_created) VALUES ('Leonie Hill', now());
INSERT INTO city(city, date_created) VALUES ('Orchard', now());
INSERT INTO city(city, date_created) VALUES ('Oxley', now());
INSERT INTO city(city, date_created) VALUES ('Bukit Timah', now());
INSERT INTO city(city, date_created) VALUES ('Grange', now());
INSERT INTO city(city, date_created) VALUES ('Holland', now());
INSERT INTO city(city, date_created) VALUES ('Chancery', now());
INSERT INTO city(city, date_created) VALUES ('Dunearn', now());
INSERT INTO city(city, date_created) VALUES ('Newton', now());
INSERT INTO city(city, date_created) VALUES ('Novena', now());
INSERT INTO city(city, date_created) VALUES ('Thomson', now());
INSERT INTO city(city, date_created) VALUES ('Toa Payoh', now());
INSERT INTO city(city, date_created) VALUES ('Potong Pasir', now());
INSERT INTO city(city, date_created) VALUES ('Machpherson', now());
INSERT INTO city(city, date_created) VALUES ('Eunos', now());
INSERT INTO city(city, date_created) VALUES ('Geylang', now());
INSERT INTO city(city, date_created) VALUES ('Kembangan', now());
INSERT INTO city(city, date_created) VALUES ('Katong', now());
INSERT INTO city(city, date_created) VALUES ('Siglap', now());
INSERT INTO city(city, date_created) VALUES ('Tanjong Rhu', now());
INSERT INTO city(city, date_created) VALUES ('Bayshore', now());
INSERT INTO city(city, date_created) VALUES ('Bedok', now());
INSERT INTO city(city, date_created) VALUES ('Chai Chee', now());
INSERT INTO city(city, date_created) VALUES ('Changi', now());
INSERT INTO city(city, date_created) VALUES ('Loyang', now());
INSERT INTO city(city, date_created) VALUES ('Pasir Ris', now());
INSERT INTO city(city, date_created) VALUES ('Pasir Ris', now());
INSERT INTO city(city, date_created) VALUES ('Simei', now());
INSERT INTO city(city, date_created) VALUES ('Tampines', now());
INSERT INTO city(city, date_created) VALUES ('Hougang', now());
INSERT INTO city(city, date_created) VALUES ('Sengkang', now());
INSERT INTO city(city, date_created) VALUES ('Ang Mo Kio', now());
INSERT INTO city(city, date_created) VALUES ('Bishan', now());
INSERT INTO city(city, date_created) VALUES ('Clementi', now());
INSERT INTO city(city, date_created) VALUES ('Upper Bukit Timah', now());
INSERT INTO city(city, date_created) VALUES ('Boon Lay', now());
INSERT INTO city(city, date_created) VALUES ('Jurong', now());
INSERT INTO city(city, date_created) VALUES ('Tuas', now());
INSERT INTO city(city, date_created) VALUES ('Bukit Batok', now());
INSERT INTO city(city, date_created) VALUES ('Bukit Panjang', now());
INSERT INTO city(city, date_created) VALUES ('Kranji', now());
INSERT INTO city(city, date_created) VALUES ('Lim Chu Kang', now());
INSERT INTO city(city, date_created) VALUES ('Admiralty', now());
INSERT INTO city(city, date_created) VALUES ('Woodlands', now());
INSERT INTO city(city, date_created) VALUES ('Tagore', now());
INSERT INTO city(city, date_created) VALUES ('Yio Chu Kang', now());
INSERT INTO city(city, date_created) VALUES ('Sembawang', now());
INSERT INTO city(city, date_created) VALUES ('Yishun', now());
INSERT INTO city(city, date_created) VALUES ('Seletar', now());
INSERT INTO city(city, date_created) VALUES ('Yio Chu Kang', now());